import streamlit as st
from io import BytesIO
import logging
import json
from pptx import Presentation
from langchain.llms import HuggingFaceEndpoint

# Set up logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# Hugging Face API token (replace with your own)
HUGGINGFACE_API_TOKEN = ""  # Replace with your Hugging Face API Token

# Streamlit app configuration
st.set_page_config(page_title="LLM-Powered Presentation Generator", page_icon="📊")
st.header("Simple LLM-Powered Presentation Generator 📊")

# Sidebar for user input
with st.sidebar:
    st.title("Create Your Presentation")
    topic = st.text_input("Enter the Topic of your Presentation:")
    presentation_type = st.selectbox("Select Presentation Type:", ["Basic", "Detailed"])

# Load the LLM for Presentation Generation
llm = HuggingFaceEndpoint(
    repo_id="meta-llama/Meta-Llama-3-8B-Instruct",
    max_new_tokens=512,
    top_k=10,
    top_p=0.95,
    typical_p=0.95,
    temperature=0.01,
    repetition_penalty=1.03,
    huggingfacehub_api_token=HUGGINGFACE_API_TOKEN
)

# Function to generate structured presentation content
def generate_presentation_content(topic, presentation_type):
    """Generates structured presentation content as a list of slides with title and content."""
    num_of_slides = 3 if presentation_type == "Basic" else 5
    try:
        # Prompt to request structured JSON response
        prompt = f"""
        Create a {num_of_slides}-slide PowerPoint presentation on the topic '{topic}'.
        Each slide should have a clear title and corresponding content.
        Respond in JSON format as a list of slides, with each slide represented as:
        [
            {{"title": "Slide 1 Title", "content": "Slide 1 content."}},
            {{"title": "Slide 2 Title", "content": "Slide 2 content."}},
            ...
        ]
        Only include content directly relevant to the topic.
        """

        response = llm.invoke(prompt)

        # Attempt to parse the response as JSON
        slides = json.loads(response)

        # Verify that each item is structured correctly as a dictionary with "title" and "content"
        if isinstance(slides, list) and all(isinstance(slide, dict) and "title" in slide and "content" in slide for slide in slides):
            return slides
        else:
            logger.error("Generated content is not in the expected format.")
            return []
    except json.JSONDecodeError as e:
        logger.error(f"Error decoding JSON response: {e}")
        return []
    except Exception as e:
        logger.error(f"Error generating content: {e}")
        return []

# Function to create a PowerPoint presentation with structured content
def create_presentation(slides, topic):
    """Creates a PowerPoint presentation from structured slide data."""
    prs = Presentation()
    title_slide_layout = prs.slide_layouts[0]  # Title slide layout
    content_slide_layout = prs.slide_layouts[1]  # Content slide layout

    # Title Slide
    title_slide = prs.slides.add_slide(title_slide_layout)
    title_slide.shapes.title.text = topic
    title_slide.placeholders[1].text = "Generated by LLM"

    # Add structured content slides
    for slide_data in slides:
        slide = prs.slides.add_slide(content_slide_layout)
        slide.shapes.title.text = slide_data["title"]
        slide.placeholders[1].text = slide_data["content"]

    return prs

# Generate button
if st.button("Generate"):
    if topic:
        with st.spinner("Generating presentation content..."):
            # Generate structured presentation content
            slides = generate_presentation_content(topic, presentation_type)
            
            # Display generated content for review
            for slide_data in slides:
                st.markdown(f"**{slide_data['title']}**\n\n{slide_data['content']}")

            # Create a PowerPoint presentation from the structured content
            prs = create_presentation(slides, topic)

            # Save presentation to BytesIO for download
            output_file = BytesIO()
            prs.save(output_file)
            output_file.seek(0)

            # Provide download button
            st.download_button(
                "Download Presentation",
                data=output_file,
                file_name="generated_presentation.pptx",
                mime="application/vnd.openxmlformats-officedocument.presentationml.presentation"
            )
    else:
        st.warning("Please enter a topic to generate the presentation.")
